/* ■■■■■■■■■■■■■■■■■■■■■ Root Layout ■■■■■■■■■■■■■■■■■■■■ */
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { Providers } from './(Redux)/provider';
import Sections from '@/components/Sections';
import Navbar from '@/components/Navbar';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// ──────────────────────────────────────────────────── 🟩 ─
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  /* ■■■■■■■■■■■■■■■■■■■■■■ Return ■■■■■■■■■■■■■■■■■■■■■■ */
  return (
    <html
      className="bg-dotted md:mx-15 lg:mx-4"
      lang="en"
    >
      <body>
        <div
          className={`m-4 min-h-[400px]  mb-20 text-sm md:m-20 bg-gray-50 rounded-2xl shadow-xl border   relative`}
        >
          {/* header */}
          <Header />
          {/* navbar */}
          <Navbar />

          {/* content */}
          <div className="min-h-[400px] bg-white pb-40">
            <Providers>{children}</Providers>
          </div>

          {/* sections */}
          <Sections />
        </div>
      </body>
    </html>
  );
}
